baseurl = "/"
author = "FRuIT-Testbed.org"
title = "FR&micro;IT Testbed"
logo = "fruit-logo.png"
logobw = "fruit-logo-bw.png"
languageCode = "en-us"
theme = "hugof"
enableRobotsTXT = true
SectionPagesMenu = ["main", "social"]

[params.meta]
description = "The Federated RaspberryPi Micro-Infrastructure Testbed"
keywords = "FRuIT, Raspberry-Pi, EPSRC, Testbed, Federated Clusters"

[params.hero]
herotitle = "FR&micro;IT"
herodescription = "The Federated RaspberryPi <span class=nobr>&micro;-Infrastructure</span> Testbed"
heroremark1 = "10,000 RaspberryPi, the largest Pi cluster in the world!"
heroremark2 = "Want to test your app on our testbed? Please <a href=mailto:webmaster@fruit-testbed.org>contact us</a>."
heroremark3 = "Want to contribute? Please visit <a href=http://picycle.org>PiCycle</a> or <a href=/join>join</a> your cluster with ours."

[params.main]
contentOneTitle = ""
contentTwoTitle = ""
contentOneBody = ""
contentTwoBody = ""

[params.footer]

[params.social]
email = "webmaster@fruit-testbed.org"
twitter = "https://twitter.com/fruit_testbed"
github = "https://github.com/fruit-testbed"


[[menu.main]]
name = "The Project"
url = "/"
weight = 1

[[menu.main]]
name = "The Team"
url = "/theteam"
weight = 2

[[menu.main]]
name = "Partners"
url = "/partners"
weight = 3

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 4

#[[menu.main]]
#name = "Blog"
#url = "/blog"
#weight = 5

[[menu.main]]
name = "PiCycle"
url = "http://picycle.org"
weight = 6

